apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app1
    spec:
      containers:
        - name: nodejs-app
          image: gcr.io/cdtest-406103/nodejs-app:latest
          ports:
            - containerPort: 3000

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: autoscaling
  namespace: default
  labels:
    app: autoscaling
spec:
  scaleTargetRef:
    kind: Deployment
    name: nodejs-app
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80